default_language_version:
  python: python3.10
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.0.277'
    hooks:
      - id: ruff
        exclude: dags/vtk_python/
        args: ["--fix","--show-fixes","--exit-non-zero-on-fix"]
  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        exclude: dags/vtk_python/
        language_version: python3.10
  - repo: https://github.com/asottile/blacken-docs
    rev: 1.15.0
    hooks:
      - id: blacken-docs
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.4.1
    hooks:
    -   id: mypy
        args: [--no-strict-optional, --ignore-missing-imports]
        exclude: dags/vtk_python/
  - repo: https://github.com/sourcery-ai/sourcery
    rev: v1.5.0
    hooks:
      - id: sourcery
        # The best way to use Sourcery in a pre-commit hook:
        # * review only changed lines:
        # * omit the summary
        # * fix issues automatically
        args: [--diff=git diff HEAD, --no-summary, --fix]
