class Config:
    PYSPARK_SUBMIT_ARGS = "--packages org.apache.spark:spark-streaming-kafka-0-10_2.12:3.4.1,org.apache.spark:spark-sql-kafka-0-10_2.12:3.4.1,com.datastax.spark:spark-cassandra-connector_2.12:3.4.0 pyspark-shell"
    SPARK_APP_NAME = "spotify_streaming"
    SPARK_DRIVER_BIND_ADDRESS = "127.0.0.1"
    SPARK_DRIVER_HOST = "127.0.0.1"
    SPARK_LOG_LEVEL = "WARN"
    KAFKA_STARTING_OFFSETS = "earliest"
    KAFKA_FAIL_ON_DATA_LOSS = "false"
    KAFKA_SPOTIFY_TOPIC = "spotify_streaming_topic"
    KAFKA_BOOTSTRAP_SERVERS = "localhost:9092"
    CASSANDRA_CONNECTION_HOST = "localhost:9042"
    CASSANDRA_KEYSPACE = "spotify_streaming"
    STREAMS_TABLE = "streams"
    USER_AGE_TABLE = "user_age"
    CHECKPOINT_LOCATION = "checkpoint"
    CHECKPOINT_ARTIST_LOCATION = "checkpoint_artist"
    TIMEZONE = "Asia/Seoul"
